project:
  type: website

website:
  title: "CatchingThomson"
  navbar:
    left: 
      - href: overview.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - href: data.qmd
        text: Data
      - href: takeaways.qmd
        text: Takeaways
      - href: report.qmd
        text: Report
      - href: poster.qmd
        text: Poster
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

