project:
  type: website

website:
  title: "Catching Thomson"
  navbar:
    left: 
      - href: index.qmd
        text: Overview
      - href: proposal.qmd
        text: Proposal
      - href: takeaways.qmd
        text: Takeaways
      - href: report.qmd
        text: Report
      - href: poster.qmd
        text: Poster


format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

