project:
  type: website

website:
  title: "CatchingThomson"
  navbar:
    left: 
      - href: overview.qmd
        text: Overview
      - href: proposal.qmd
        text: Project Proposal
      - href: data.qmd
        text: Data Preperation
      - href: lesson.qmd
        text: Lessons Learnt
      - href: report.qmd
        text: Project Report
      - href: poster.qmd
        text: Project Poster
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

